### ISSUE TITLE
作者您好，请问一下这个attn_path = os.path.join(data_dir_l, 'attn_mask', '{}.pt'.format(slide_id.rstrip('.svs')))里面的attn_mask在哪里生成的？

### ISSUE THREAD

**Issue by junjianli106** [Jiangbo-Shi/MG-Trans#3]
作者您好，请问一下这个attn_path = os.path.join(data_dir_l, 'attn_mask', '{}.pt'.format(slide_id.rstrip('.svs')))里面的attn_mask在哪里生成的？找了半天没找到

https://github.com/Jiangbo-Shi/MG-Trans/blob/26d323784773286f4878f9d25f7c2a86e493bac8/datasets/dataset_generic.py#L346C1-L346C96

**Comment by Jiangbo-Shi** [comment]
Thanks. We have added the script for generating the atten_mask. Please see the file 'patch_alignment.py'.
