### ISSUE TITLE
CA-MAP interpretability analysis

### ISSUE THREAD

**Issue by Yicijiuhaobala** [Jiangbo-Shi/MG-Trans#4]
Can the attention graph code for CA-MAP interpretability analysis be open sourced? Thx

**Comment by Jiangbo-Shi** [comment]
We utilize the script proposed by CLAM for the interpretability analysis. Please refer to "https://github.com/mahmoodlab/CLAM/blob/master/create_heatmaps.py".

**Comment by superli6** [comment]
> Can the attention graph code for CA-MAP interpretability analysis be open sourced? Thx

Did you successfully reproduce the heatmap?
